spring:
  application:
    name: dada-be

  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.cob5myt.mongodb.net/?appName=Cluster0
  mongodb:
    uri: mongodb+srv://admin:admin@cluster0.cob5myt.mongodb.net/?appName=Cluster0

server:
  port: 8080
  error:
    include-message: always


springdoc:
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs